# Generated by Django 6.0.3 on 2026-03-24 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('Portero', 'Portero'), ('Defensa', 'Defensa'), ('Mediocampista', 'Mediocampista'), ('Delantero', 'Delantero')], default='Mediocampista', max_length=50)),
                ('ranking', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Jugador',
                'verbose_name_plural': 'Perfiles de Jugadores',
            },
        ),
    ]
