# Generated by Django 6.0.4 on 2026-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0002_perfiljugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='distrito',
            field=models.CharField(default='Lima', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partido',
            name='nombre_encuentro',
            field=models.CharField(default='Por definir', max_length=100),
            preserve_default=False,
        ),
    ]
