# Generated by Django 6.0.4 on 2026-04-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0003_partido_distrito_partido_nombre_encuentro'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='cupos_max',
            field=models.IntegerField(default=12),
        ),
    ]
