# Generated by Django 6.0.4 on 2026-04-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0005_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='cupos_disponibles',
        ),
        migrations.AddField(
            model_name='partido',
            name='cupos_inscritos',
            field=models.IntegerField(default=0),
        ),
    ]
