# Generated by Django 6.0.4 on 2026-04-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0006_remove_partido_cupos_disponibles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='nombre_jugador',
            new_name='usuario',
        ),
    ]
