# Generated by Django 6.0.4 on 2026-04-10 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0007_rename_nombre_jugador_inscripcion_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiljugador',
            name='apodo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apodo de Crack'),
        ),
        migrations.AddField(
            model_name='perfiljugador',
            name='distrito',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfiljugador',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='perfiljugador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
