# Generated by Django 6.0.4 on 2026-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0008_perfiljugador_apodo_perfiljugador_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiljugador',
            name='partidos_jugados',
            field=models.IntegerField(default=0),
        ),
    ]
