# Generated by Django 6.0.4 on 2026-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0009_perfiljugador_partidos_jugados'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiljugador',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/default_user.png', null=True, upload_to='perfiles/', verbose_name='Foto de Crack'),
        ),
    ]
