# Generated by Django 6.0.4 on 2026-04-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0010_perfiljugador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiljugador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Crack'),
        ),
    ]
