# Generated by Django 6.0.4 on 2026-04-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0011_alter_perfiljugador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='equipo',
            field=models.CharField(choices=[('A', 'Equipo A'), ('B', 'Equipo B')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='posicion_numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
