# Generated by Django 6.0.4 on 2026-04-14 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0013_alter_inscripcion_partido_alter_inscripcion_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONDUCTA', 'Conducta Antideportiva'), ('FALLO', 'Fallo del Sistema / Bug'), ('PAGO', 'Problema con Pago/Voucher'), ('OTRO', 'Otro')], default='CONDUCTA', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Detalles del reporte')),
                ('captura', models.ImageField(blank=True, null=True, upload_to='reportes/', verbose_name='Evidencia (Opcional)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_PROCESO', 'En Revisión'), ('RESUELTO', 'Resuelto'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Comentarios del Administrador')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_futbol.partido')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_reportes', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
