# Generated by Django 6.0.4 on 2026-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0014_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('CONDUCTA', 'Conducta Antideportiva'), ('FALLO', 'Fallo del Sistema / Bug'), ('PAGO', 'Problema con Pago/Voucher'), ('OTRO', 'Otro')], default='CONDUCTA', max_length=50),
        ),
    ]
