# Generated by Django 6.0.4 on 2026-04-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_futbol', '0015_alter_reporte_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiljugador',
            old_name='ranking',
            new_name='estrellas',
        ),
        migrations.AddField(
            model_name='perfiljugador',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('nivel', models.CharField(default='Bronce', max_length=20)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_futbol.perfiljugador')),
            ],
            options={
                'ordering': ['-puntos'],
            },
        ),
    ]
